#!/usr/bin/env node

/**
 * @description [zh-CN] IPC 类型自动生成器 — 扫描主进程 handler，生成渲染进程类型文件
 * @description [zh-TW] IPC 型別自動生成器 — 掃描主程序 handler，生成渲染程序型別檔案
 * @description [en] IPC type auto-generator — scans main process handlers, generates renderer type file
 * @description [ja] IPC 型自動生成 — メインプロセスの handler をスキャンし、レンダラーの型ファイルを生成
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import ts from "typescript";

const IPC_DIR = resolve(process.cwd(), "main-process/ipc");
const OUTPUT = resolve(
  process.cwd(),
  "renderer-process/shared/services/ipc.generated.ts"
);

interface ChannelInfo {
  channel: string;
  args: string;
  returnType?: string;
}

/**
 * @description [zh-CN] 从文件中提取 IPC 通道信息
 * @description [zh-TW] 從檔案中提取 IPC 通道資訊
 * @description [en] Extract IPC channel info from a file
 * @description [ja] ファイルから IPC チャンネル情報を抽出
 */
function extractChannels(filePath: string) {
  const source = readFileSync(filePath, "utf-8");
  const sourceFile = ts.createSourceFile(
    filePath,
    source,
    ts.ScriptTarget.Latest,
    true
  );

  const handlers: ChannelInfo[] = [];
  const listeners: ChannelInfo[] = [];

  function visit(node: ts.Node) {
    if (
      ts.isCallExpression(node) &&
      ts.isIdentifier(node.expression)
    ) {
      const fnName = node.expression.text;
      const isHandler = fnName === "defineHandlers";
      const isListener = fnName === "defineListeners";

      if ((isHandler || isListener) && node.arguments.length > 0) {
        const arg = node.arguments[0];
        if (ts.isObjectLiteralExpression(arg)) {
          for (const prop of arg.properties) {
            if (ts.isPropertyAssignment(prop) || ts.isMethodDeclaration(prop)) {
              const channelName = getPropertyName(prop);
              if (!channelName) continue;

              const fn = ts.isPropertyAssignment(prop) ? prop.initializer : prop;
              const params = extractParams(fn, source);
              const ret = isHandler ? extractReturnType(fn, source) : undefined;

              const target = isHandler ? handlers : listeners;
              target.push({
                channel: channelName,
                args: params,
                returnType: ret,
              });
            }
          }
        }
      }
    }

    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return { handlers, listeners };
}

function getPropertyName(prop: ts.ObjectLiteralElementLike): string | undefined {
  if (prop.name) {
    if (ts.isStringLiteral(prop.name)) return prop.name.text;
    if (ts.isIdentifier(prop.name)) return prop.name.text;
    if (ts.isComputedPropertyName(prop.name)) return undefined;
  }
  return undefined;
}

/**
 * @description [zh-CN] 提取函数参数类型（跳过第一个 event 参数）
 * @description [zh-TW] 提取函數參數型別（跳過第一個 event 參數）
 * @description [en] Extract function parameter types (skip first event param)
 * @description [ja] 関数パラメータの型を抽出（最初の event パラメータをスキップ）
 */
function extractParams(fn: ts.Node, source: string): string {
  let params: ts.NodeArray<ts.ParameterDeclaration> | undefined;

  if (ts.isArrowFunction(fn) || ts.isFunctionExpression(fn)) {
    params = fn.parameters;
  } else if (ts.isMethodDeclaration(fn)) {
    params = fn.parameters;
  }

  if (!params || params.length <= 1) return "[]";

  const argTypes = params.slice(1).map((p) => {
    if (p.type) {
      return source.slice(p.type.pos, p.type.end).trim();
    }
    return "any";
  });

  return `[${argTypes.join(", ")}]`;
}

/**
 * @description [zh-CN] 提取函数返回值类型
 * @description [zh-TW] 提取函數回傳值型別
 * @description [en] Extract function return type
 * @description [ja] 関数の戻り値の型を抽出
 */
function extractReturnType(fn: ts.Node, source: string): string {
  if (ts.isArrowFunction(fn) || ts.isFunctionExpression(fn) || ts.isMethodDeclaration(fn)) {
    if (fn.type) {
      return source.slice(fn.type.pos, fn.type.end).trim();
    }
  }
  return "any";
}

/**
 * @description [zh-CN] 生成输出文件内容
 * @description [zh-TW] 生成輸出檔案內容
 * @description [en] Generate output file content
 * @description [ja] 出力ファイルの内容を生成
 */
function generateOutput(
  handlers: ChannelInfo[],
  listeners: ChannelInfo[]
): string {
  const handleEntries = handlers
    .map(
      (h) =>
        `  "${h.channel}": { args: ${h.args}; return: ${h.returnType ?? "void"} };`
    )
    .join("\n");

  const onEntries = listeners
    .map((l) => `  "${l.channel}": { args: ${l.args} };`)
    .join("\n");

  return `/**
 * @description [zh-CN] ⚠️ 此文件由 CLI 自动生成，请勿手动修改。运行 \`pnpm gen:ipc\` 重新生成
 * @description [zh-TW] ⚠️ 此檔案由 CLI 自動生成，請勿手動修改。執行 \`pnpm gen:ipc\` 重新生成
 * @description [en] ⚠️ This file is auto-generated by CLI. Do not edit manually. Run \`pnpm gen:ipc\` to regenerate
 * @description [ja] ⚠️ このファイルは CLI により自動生成されます。手動で編集しないでください。\`pnpm gen:ipc\` で再生成
 */

// ---- Handle（渲染进程 invoke → 主进程 handle） ----
export interface IpcHandleMap {
${handleEntries}
}

// ---- On（渲染进程 send → 主进程 on） ----
export interface IpcOnMap {
${onEntries}
}

// ---- Send（主进程 send → 渲染进程 on） ----
export interface IpcSendMap {}

export function ipcInvoke<K extends keyof IpcHandleMap>(
  channel: K,
  ...args: IpcHandleMap[K]["args"]
): Promise<IpcHandleMap[K]["return"]> {
  return window.ipcRenderer.invoke(channel, ...args);
}

export function ipcSend<K extends keyof IpcOnMap>(
  channel: K,
  ...args: IpcOnMap[K]["args"]
): void {
  window.ipcRenderer.send(channel, ...args);
}

export function ipcOn<K extends keyof IpcSendMap>(
  channel: K,
  listener: (event: any, ...args: IpcSendMap[K]["args"]) => void
): () => void {
  window.ipcRenderer.on(channel, listener);
  return () => window.ipcRenderer.removeListener(channel, listener);
}
`;
}

// ---- 主逻辑 ----

function main() {
  const files = readdirSync(IPC_DIR).filter(
    (f) => f.endsWith(".ts") && f !== "index.ts"
  );

  const allHandlers: ChannelInfo[] = [];
  const allListeners: ChannelInfo[] = [];

  for (const file of files) {
    const filePath = resolve(IPC_DIR, file);
    const { handlers, listeners } = extractChannels(filePath);
    allHandlers.push(...handlers);
    allListeners.push(...listeners);
  }

  const output = generateOutput(allHandlers, allListeners);
  writeFileSync(OUTPUT, output);
  console.log(`  ✓ Generated ${OUTPUT}`);
  console.log(`    ${allHandlers.length} handle channels`);
  console.log(`    ${allListeners.length} on channels`);
}

main();
