/**
 * @description [zh-CN] ⚠️ 此文件由 CLI 自动生成，请勿手动修改。运行 `pnpm gen:ipc` 重新生成
 * @description [zh-TW] ⚠️ 此檔案由 CLI 自動生成，請勿手動修改。執行 `pnpm gen:ipc` 重新生成
 * @description [en] ⚠️ This file is auto-generated by CLI. Do not edit manually. Run `pnpm gen:ipc` to regenerate
 * @description [ja] ⚠️ このファイルは CLI により自動生成されます。手動で編集しないでください。`pnpm gen:ipc` で再生成
 */

// ---- Handle（渲染进程 invoke → 主进程 handle） ----
export interface IpcHandleMap {
  "store:getAll": { args: []; return: ElectronStore.Options };
  "store:get": { args: [key: keyof ElectronStore.Options]; return: ElectronStore.Options[keyof ElectronStore.Options] };
}

// ---- On（渲染进程 send → 主进程 on） ----
export interface IpcOnMap {
  "store:set": { args: [key: keyof ElectronStore.Options, value: ElectronStore.Options[keyof ElectronStore.Options]] };
  "window:open": { args: [name: string] };
  "window:close": { args: [name: string] };
  "window:minimize": { args: [name: string] };
  "window:maximize": { args: [name: string] };
  "window:unMaximize": { args: [name: string] };
}

// ---- Send（主进程 send → 渲染进程 on） ----
export interface IpcSendMap {}

/**
 * @description [zh-CN] 类型安全的 invoke 调用
 * @description [zh-TW] 型別安全的 invoke 呼叫
 * @description [en] Type-safe invoke call
 * @description [ja] 型安全な invoke 呼び出し
 */
export const ipcInvoke = <K extends keyof IpcHandleMap>(
  channel: K,
  ...args: IpcHandleMap[K]["args"]
): Promise<IpcHandleMap[K]["return"]> => {
  return window.ipcRenderer.invoke(channel, ...args);
};

/**
 * @description [zh-CN] 类型安全的 send 调用
 * @description [zh-TW] 型別安全的 send 呼叫
 * @description [en] Type-safe send call
 * @description [ja] 型安全な send 呼び出し
 */
export const ipcSend = <K extends keyof IpcOnMap>(
  channel: K,
  ...args: IpcOnMap[K]["args"]
): void => {
  window.ipcRenderer.send(channel, ...args);
};

/**
 * @description [zh-CN] 类型安全的事件监听
 * @description [zh-TW] 型別安全的事件監聽
 * @description [en] Type-safe event listener
 * @description [ja] 型安全なイベントリスナー
 */
export const ipcOn = <K extends keyof IpcSendMap>(
  channel: K,
  listener: (event: any, ...args: IpcSendMap[K]["args"]) => void
): (() => void) => {
  window.ipcRenderer.on(channel, listener);
  return () => window.ipcRenderer.removeListener(channel, listener);
};
